### PR TITLE
Implement a newer node version

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Submitted for the approval of the Midnight Society

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I'm not quite sure this is the best approach (changing it for everyone) but in case we wanted to up our version this might be the place to do it.

**Comment by borkweb** [comment]
This feels like the right place, but we'll need to make sure all of our plugins support the newer npm/node version first. That's something that @paulmskim has been talking about looking into!

**Comment by lucatume** [comment]
I'd not replace the existing `node` container, but use build ARGs to make it dynamic and build the `node` version we need. Let's add a second `npm` service, say `npm_12` and use that explicitly where required.

**Comment by lucatume** [comment]
@sc0ttkclark I'm closing this one as it seems to have been addressed in this one: https://github.com/moderntribe/tric/pull/43

If that is not the case, please re-open this PR.

**Pull request closed without merging**
